### PR TITLE
Feature | Support for Send API V3.1

### PR DESCRIPTION
**Pull request by EstebanBorai**

### CODE REVIEW

**Comment by zmontgo** [comment]
How's the progress coming along? If you need any help let me know!

**Comment by EstebanBorai** [comment]
> How's the progress coming along? If you need any help let me know!

Hi @zmontgo!

I would really appreciate help and suggestions on this feature, I find the current architecture of this crate a bit difficult to scale and would prefer to re implement it.

The truth is that I created this crate when I was learning Rust and nowadays I would change many aspects from it.
I can open a Discussion provide input there and then move into actionable. I would close this PR and get started from a fresh state.

Let me know what do you think, thank you so much!

**Comment by zmontgo** [comment]
Hey!

I am learning Rust myself, so I look forward to learning from you!

I will say, if you feel the codebase isn't working well for you I'd opt to get started from a fresh state. I'd be happy to be engaged in that process.

**Comment by EstebanBorai** [comment]
> Hey!
> 
> 
> 
> I am learning Rust myself, so I look forward to learning from you!
> 
> 
> 
> I will say, if you feel the codebase isn't working well for you I'd opt to get started from a fresh state. I'd be happy to be engaged in that process.

Im glad to have have your help in this crate. Of course, let me open a discussion so we can put our ideas together and then define tasks to achieve what we want to build.

I will ping you later today via repository discussions.

Thank you so much!

**Comment by zmontgo** [comment]
@EstebanBorai sounds great, thanks! I look forward to it and already have quite a few ideas as to what the client may look like. I think I've come up with an intuitive, elegant, and pragmatic solution.

**Pull request closed without merging**
