### PR TITLE
feat: support custom headers

### PR DESCRIPTION
**Pull request by zmontgo**
Allows for creating custom headers. I've tested this and it works.

I'm not sure I did the documentation comments correctly.

### CODE REVIEW

**Comment by zmontgo** [comment]
The Cargo.lock update was necessary since it appeared some older package was searching for OpenSSL in the wrong place.

**Comment by zmontgo** [comment]
I also realize that this is a breaking change. Should I change it to work with existing codebases that depend on this package?

**Comment by EstebanBorai** [comment]
Incredible @zmontgo! That was a very quick start! 🚀 

With regards to the `Cargo.lock`, I think we can remove it from the repo. I got a suggestion [in this issue comment](https://github.com/EstebanBorai/network-interface/pull/9#issuecomment-1196316398), which pointed out the [following `Cargo Book` article](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html#cargotoml-vs-cargolock) where I learned that library crates can have the `Cargo.lock` file omitted, so feel free to remove it.

If you want to, feel free to open another PR (so we keep changes scoped), where these changes gets applied.

I did the same for the network-interface crate in this commit: https://github.com/EstebanBorai/network-interface/commit/5c4d57a12bbd04a2831bc562ddb1cb9ed40f1c24.

**Comment by EstebanBorai** [comment]
> I also realize that this is a breaking change. Should I change it to work with existing codebases that depend on this package?

In my opinion, it would be great to keep compatibility with current codebase, so we can release this feature before getting our hands to work on support for Send API v3.1.

**Comment by zmontgo** [comment]
Sounds good. Just give me a minute to upload a new change to make sure people don't need to change their `Message::new` function once we pull these changes.

**Comment by EstebanBorai** [comment]
@zmontgo This repository uses _Squash and Merge_ as PR merge strategy, along with _Default commit to PR title_.

I try to keep commits following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) convention, what do you think about renaming the PR title to be something similar to: `feat: support custom headers`? This way the commit will look like `feat: support custom headers (#57)` when we get it merged to `main`.

**Comment by zmontgo** [comment]
@EstebanBorai sorry I'm only now seeing this. I need to work on my commit messages. Let me change that now.

**Comment by EstebanBorai** [comment]
> @EstebanBorai sorry I'm only now seeing this. I need to work on my commit messages. Let me change that now.

No worries! Thanks so much!

**Review by EstebanBorai — COMMENTED** [review]
Looking great! Can you help me running `cargo fmt` and then `cargo clippy`? Looks like we have some CI issues to solve which are related to these workflows. After that we are ready to go!

**Comment by EstebanBorai** [comment]
> Looking great! Can you help me running `cargo fmt` and then `cargo clippy`? Looks like we have some CI issues to solve which are related to these workflows. After that we are ready to go!

Actually I see we have issues with `build` and `fmt`.

**Comment by EstebanBorai** [comment]
I can see the `build` workflow is failing because we pass `--locked` to the `cargo build` command. This is because we removed the `Cargo.lock` file and we are trying to regenerate a new one, which makes `build` complain when `--locked` is passed as an argument to the command.

You can get it fixed by removing `--locked` from here: https://github.com/EstebanBorai/mailjet-rs/blob/7681eed9ea8603485f508614e00d2fa7d5d14eaa/.github/workflows/build.yml#L30

**Comment by zmontgo** [comment]
Hey, both should be fixed.

**Review by EstebanBorai — APPROVED** [review]
Great @zmontgo! I will draft a release soon!

**Pull request merged**
